print('naaminvoer')
name = input('geef uw naam ')
adress = input('geef uw adress ')
postcode = input('geef uw postcode ')
woonplaats = input('geef uw woonplaats ')
print("")
print("")
print("")
print(" ---------------------------")
print("|  hallo "+name)
print("|  Adress: "+adress)
print("|  postcode: "+postcode)
print("|  woonplaats: "+woonplaats)
print(" ---------------------------")